elastic:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - docker_volumes/elasticsearch_data:/usr/local/elasticsearch/data
api:
  build: ./api
  command: bash ./deploy/start.sh
  volumes:
    - api:/api
  ports:
    - "4567:4567"
  links:
    - elastic
  environment:
    - ORIGIN_REPO=switzersc/atlanta-food-data
    - ELASTIC_HOST=http://elastic:9200
